version: '3.3'
services:
  hrnet:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 6006:6006
      - 8888:8888
    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /vinai-autopilot:/vinai-autopilot
    devices:
      - /dev/video0:/dev/video0
    environment:
      - DISPLAY=$DISPLAY
